server:
  host: 127.0.0.1
  port: 30001
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: false

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 5

prompt:
  positive: |
    1girl, solo, 
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$expressive_h$$,
    $$common$$,
    $$posture$$,
    $$act$$,   
    $$act_sub$$,
    $$act_by$$,
    $$body$$,    
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,    
    $$scene$$,
  negative: |
    (score_5,score_4,score_3,score_2,score_1),
    (text:1.2), (logo:1.2), (watermark:1.2),
    (bad anatomy:1.2),
    (extra legs：1.2),(extra hands:1.2), 
    (extra digits:1.2),(fewer digits;1.2),
  params_cycle: -1
  params_pos_1:
    character_lora: "<lora:clorinde_pony:0.9>,clorinde_(genshin_impact)"
    character: "white gloves,tricorne,black pantyhose,pencil skirt,black jacket,fold-over boots,ascot,thigh strap,white shirt,underbust,blue cape"
    expressive_h: "<lora:Expressive_H:1>,expressiveh"
    common: "motion lines"
    posture: [
      "licking penis",
    ]
    act: [
      "kneeling",
      "squatting",
      "lying",
      "all fours",
      "69, lying",
      "blowjob, felatio, oral, penis, ass, looking at the viewer, hetero, lying",
      ""
    ]
    act_sub: [
      "grabbing own breast",
      "grabbing own breast, deep throat",
      "hand job",
      "masturbation, fingering",
      "orgy, handjob",
      ""
    ]
    act_by: [
      "hand on head",
      "hand on head, deep throat",
      "deep throat",
      "deep throat rolling eyes",
      "", ""
    ]
    body: [
      "half nude, (saliva trail:0.5), (saliva:0.5), (cum:0.5)"
    ]
    perspective: [
      "from above, pob",
      "from side",
      "from below",

    ]
    facial_expression: [
      "blush",
      "blush, embarrassed"
    ]
    facial_expression_sub: [
    ]
    scene: [
      "simple background, dark, shadow and light"
    ]


sampler:
  active: true
  name: "Euler a"
  steps: 26
  cfg_scale: 5
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 2
  use_async: true
  metadata_key: "b_pox_b"

extra:
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  #file_format: "./output/%Y%m%d/belle/0/%H%M%S"
  file_format: "D:/snapshot/character/hoyoverse/genshin/clorinde/20240617/3/%H%M%S"
  file_extension: "png"

