server: '#__file__#:../server.yaml'

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 10

prompt:
  positive: |
    1girl, solo, 
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$expressive_h$$,
    $$nsfw_common$$,
    $$nsfw_posture$$,
    $$nsfw_act$$,    
    $$nsfw_act_by$$,
    $$nsfw_body$$,    
    $$character_lora$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,    
    $$scene$$,
  negative: |
    (score_5,score_4,score_3,score_2,score_1),
    (text:1.2), (logo:1.2), (watermark:1.2),
    (bad anatomy:1.2),
    (extra legs：1.2),(extra hands:1.2), 
    (extra digits:1.2),(fewer digits;1.2),
  params_cycle: -1
  params_pos_1:
    character_lora: "<lora:Belle_from_Zenless_Zone_Zero:0.95>, belle (zenless zone zero)"
    character: "earrings,jewelry,shirt,black shirt,long sleeves,hooded jacket"
    expressive_h: "<lora:Expressive_H:1>,expressiveh"
    nsfw_common: "motion lines, hetero, sex"
    nsfw_posture: [
      "top-down bottom-up, face_focus, bottomless",
      "top-down bottom-up, face_focus, bottomless, front view",
      "top-down bottom-up, bottomless, from_side",
      "bent over desk, pov, skirt pulled down, panty pulled down, looking back, hands on ass, pussy, pussy juice, pov",
      "bent over desk, pov, skirt pulled down, panty pulled down, looking back, hands on ass, doggy style sex, pussy juice, penetration, pov",
      "squatting, no panties, spread knees, clothes lift, lifted by self, from below",
      "squatting",
      "skirt lift, lifted by self, bottomless, no panties",
      "lying on back, pov, arms up,arms bound, rope, head tilt, knees up, cunninggulus, waist grab",
      "lying on back, from side, arms up,arms bound, rope, head tilt, knees up, cunninggulus, waist grab",
      "lying on side, penetration, vaginal",
      "lying on stomach, sex from behind, hand on head",
      "licking penis, fellatio, hand on head",
      "licking penis, fellatio, hand on head, pov, from above",
      "licking penis, nipples, from side, kneeling, hand on head,",
      "licking penis, deep throat",
      "licking penis, handjob, orgy",
      "licking penis, pov",
      "licking penis, deep throat, pov",
      "licking penis, 69",
      "slapping with penis on face",
      "sitting on face, boy on top",
      "cock tease, grabbing hair",
      "open mouth, kneeling, cum on face, cum in mouth, from above",
      "kneeling, spreading own ass",
      "sex_from_behind, against wall, hands on wall, from back, from above",
      "standing sex",
      "standing sex, split, leg up",
      "female masturbation, grabbing own breast, bathing, topless",
      "female masturbation, spread legs, female masturation, spread pussy by self",
      "missionary sex, pov, grabbing another's breast",
      "standing missionary",
      "doggy style, kneeling",
      "sex from behind, from below",
      "cowgirl",
      "cowgirl, grabbing own breast",
      "reverse cowgirl, slutty",
      "girl on top, legs lock",
      "french kiss, missionary, faceless male",
      "breast sex, titfucking, pov, breasts, nipple, penis",
      "foggy, exposed_pussy,vaginal, riding a dick, jizz oozing out of pussy, cum, orgasm,",
      "wariza, w_sitting, ass, ass_focus, feet",
      "wariza, w_sttiing, pov, from_above",
      "spreading own ass, from behind, pov",
      "spread pussy, spread legs, looking to the side, v hand, pussy juice",
      "ahegao, peace sign, v hands, v",
      "spooning",
      "orgy, double penetration",
      "orgy, penetration, licking penis",
      "fingering, pussy, pussy juice",
      "fingering, from back, ass, pussy, pussy juice",
    ]
    nsfw_act: [
      "fellatio",
      "sex",
      "arms up",
      "arms behind back",
      "grabbing own breasts",
      "grabbing own ass",
      "masturbation",
      "fingering",
      "",
    ]
    nsfw_act_sub: [
    ]
    nsfw_act_by: [
      "grabbing another's breast",
      "grabbing another's ass",
      "grabbing another's hair, hair_pull",
      "hand on head",
      "hand on ass",
      "", "", "", "", "", "",
    ]
    nsfw_body: [
      "nipples, breasts",
      "pussy, pussy juice, nipples, breasts",
      "pussy, pussy juice",
      "slap mark, bottomless, ass",
      "slap mark, topless, breasts, nipples",
      "half nude",
      "nude",
      "choker, bondage, rope, bdsm",
      "lingerie, lace",
      "torn clothes, half nude",
      "mouth ball gag",
      "black blindfold",
      "sex slave, dog leash, dog lead",
      "",
    ]
    perspective: [
    ]
    facial_expression: [
      "blush",
    ]
    facial_expression_sub: [
      "open mouth",
      "open mouth, tongue out",
      "open mouth, embarrassed",
      "embarrassed",
      "looking to the side, embarrassed",
    ]
    scene: [
      "bedroom", "alley", "simple background", "street, night"
    ]



sampler:
  active: true
  name: "Euler a"
  steps: 20
  cfg_scale: 5
  seed: -1

upscaler:
  enable: false
  scale: 1.2
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 2
  use_async: true

output:
  file_format: "./output/%Y%m%d/belle/0/%H%M%S"
  file_extension: "png"

