server:
  host: 127.0.0.1
  port: 30001
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: false

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 5

prompt:
  positive: |
    1girl, solo,   
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$expressive_h$$,
    $$common$$,
    $$posture$$,
    $$act$$,   
    $$act_sub$$,
    $$act_by$$,
    $$body$$,    
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,    
    $$scene$$,
  negative: |
    (score_5,score_4,score_3,score_2,score_1),
    pony, muscular, censored, furry, child, kid, chibi, 3d, monochrome,
    (text:1.2), (logo:1.2), (watermark:1.2),
    (bad anatomy:1.2),
    (extra legs：1.2),(extra hands:1.2), 
    (extra digits:1.2),(fewer digits;1.2),
  params_cycle: -1
  params_pos_1:
    character_lora: "<lora:Char-ZZZ-Nicole-Pony-V1:0.85>,nicole demara"
    character: |
      tube top,single thighhigh,short shorts,cropped jacket,
      belt boots, hair ribbon, hairclip,earrings,single sock,
      high belt, thigh strap, detached sleeves,doll,black collar,
    expressive_h: "<lora:Expressive_H:1>,expressiveh"
    common: "(motion lines:0.9), blush"
    posture: [
      "orgy, penetration, picking penis, double penetration, hand job, blow job, pussy juice, pussy",
      # "arms up, arms bound, rope, head tilt, knees up, spread legs, black blindfold, bottomless, pussy juice, pussy, from above, front view, lying on back, mouth gag, saliva, fingering",
      # "cowgirl position, penetration, vaginal, grabbing own breast, topless, open mouth, tongue out, pussy juice",
      # "reverse cowgirl position, penetration, vaginal, ass, slap mark, bottomless, pussy juice, grabbing another's ass, back",
    ]
    posture2: [
      "licking penis, fellatio, hand on head",
      "licking penis, fellatio, hand on head, pov, from above",
      "licking penis, nipples, from side, kneeling, hand on head,",
      "licking penis, deep throat",
      "licking penis, handjob, orgy",
      "licking penis, pov",
      "licking penis, pov, from above",
      "licking penis, deep throat, pov",
      "licking penis, 69, mutual fellatio",
      "licking penis, bottomless, masturbation, squatting",
      "licking penis, bottomless, spread pussy by own hand",
      "licking penis, topless, grabbing own breast",
    ]
    act: [
    ]
    act_sub: [
    ]
    act_by: [
    ]
    body: [
      "(nude:0.5), (saliva trail:0.5)",
      "(nude:0.75), (saliva trail:0.5)",
      "nude, (saliva trail:0.5)",
    ]
    perspective: [
    ]
    facial_expression2: [
      "tears",
      "ahegao",
      "facepalm",
      "rolling eyes",
      "embarrass",
      "open mouth",
      "open mouth, tongue out",
      "slave, dog leash"
    ]
    facial_expression_sub: [
    ]
    scene: [
      # "bedroom", "alley", "simple background, light", "simple background, dark", "bathroom",
      "alley, light and shadow"
    ]


sampler:
  active: true
  name: "Euler a"
  steps: 20
  cfg_scale: 5.75
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 2
  use_async: true
  metadata_key: "b_pox_b"

extra:
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  #file_format: "./output/%Y%m%d/belle/0/%H%M%S"
  file_format: "D:/snapshot/character/hoyoverse/zenless_zone_zero/nicole/%Y%m%d/1/%H%M%S"
  file_extension: "png"

