server:
  host: 127.0.0.1
  port: 30001
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: false

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 5

prompt:
  positive: |
    1girl, solo, 
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$expressive_h$$,
    $$common$$,
    $$posture$$,
    $$act$$,   
    $$act_sub$$,
    $$act_by$$,
    $$body$$,    
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,    
    $$scene$$,
  negative: |
    (score_5,score_4,score_3,score_2,score_1),
    (text:1.2), (logo:1.2), (watermark:1.2),
    (bad anatomy:1.2),
    (extra legs：1.2),(extra hands:1.2), 
    (extra digits:1.2),(fewer digits;1.2),
  params_cycle: -1
  params_pos_1:
    character_lora: "<lora:ZenlessZoneZeroPDXL:0.9>"
    character: [
      "nicole demara,green eyes,pink hair,hair ornament,hair ribbon,hairclip,long hair,mole under eye,two side up,black footwear,black ribbon,black shorts,black socks,black thighhighs,boots,crop top,earrings,jewelry,kneehighs,nail polish,necklace,o-ring,short shorts,single kneehigh,single sock,single thighhigh,socks,thigh strap,thighhighs,torn clothes",
      # "corin wickes, green hair, purple eyes, hair between eyes, twintails, maid headdress, puffy short sleeves, black dress, white apron, maid, nsfw",
      # "soukaku, red eyes, blue skin, white hair, short hair, horns, oni, black choker, jacket, white collared shirt, black tie, black skirt",
      # "hoshimi miyabi, fox ears, red eyes, black hair, long hair, jacket, black skirt, black pantyhose",
      # "ellen joe, black hair, colored inner hair, multicolored hair, red eyes, short hair, black pantyhose, black shirt, black skirt, ear piercing, fins, maid apron, maid headdress, pantyhose, piercing, puffy short sleeves, puffy sleeves, short sleeves, skirt, two-tone hair, wrist cuffs, maid",
      # "nekomiya mana, cat ears, red eyes, neck bell, hairband, two tails, detached sleeves, black thighhighs, ponytail, red leotard, leotard under clothes, black shorts, hair ribbon, boots, forehead mark",
      # "anby demara, orange eyes, short hair, white hair, bare shoulders, black gloves, black skirt, black thighhighs, fingerless gloves, gloves, green jacket, headphones, jacket, navel, skirt, stomach, thighhighs",
      # "koleda belobog, eyepatch, red eyes, red hair, twintails, fake animal ears, flame print, midriff, white jumpsuit, jumpsuit around waist, fingerless gloves",
    ]
    expressive_h: "<lora:Expressive_H:1>,expressiveh"
    common: ""
    posture: [
      "(pov), (from behind), (from above) ,(ass), (pussy),(pussy juice), (bottomless)",
      "(pov), (from behind), (ass), (pussy),(pussy juice), (bottomless)",
      "(pov), (from behind), (distant), (ass), (pussy),(pussy juice), (bottomless)",
    ]
    act: [
      # "vaginal object insertion (sex toy)",
      # "vaginal, (penetration), penis, sex",
      "cum in pussy, cum, spread pussy",
      # "fingering",
      # "panty pull",
      # "",
    ]
    act_sub: [
      "slap mark (on ass)",
      "tattoo",
      ""
    ]
    act_by: [
      "grabbing own ass, hand on ass",
      "grabbing another's ass, hand on ass",
      "grabbing another's hair",
      "spread pussy",
      "",
    ]
    body: [
    ]
    perspective: [
    ]
    facial_expression: [
      "blush",
      "blush, embarrass, open mouth, saliva trail, (looking back:0.9)",
      "blush, embarrass, open mouth, saliva trail, tongue out, (looking back:0.9)",
    ]
    facial_expression_sub: [
    ]
    scene: [
      "window, light and shadow",
      "bed, light and shadow",
    ]


sampler:
  active: true
  name: "Euler a"
  steps: 23
  cfg_scale: 6
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 2
  use_async: true
  metadata_key: "b_pox_b"

extra:
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  #file_format: "./output/%Y%m%d/belle/0/%H%M%S"
  file_format: "D:/snapshot/character/hoyoverse/zenless_zone_zero/nicole/%Y%m%d/0_ass/%H%M%S"
  file_extension: "png"

