server:
  host: 127.0.0.1
  port: 30001
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: false

image_latent:
  width: 1216
  height: 1216
  batch_size: 1
  batch_count: 3

prompt:
  positive: |
    (score_9, score_8_up, score_7_up, source_anime, rating_all, rating_explicit),
    $$character_lora$$,    
    $$character_cloth$$,
    $$phone_lora$$,
    $$posture$$,
    $$facial_expression$$,    
    $$scene$$,
  negative: |
    (score_5,score_4,score_3,score_2,score_1),
    (text:1.2), (logo:1.2), (watermark:1.2),
    (bad anatomy:1.2),
    (extra legs：1.2),(extra hands:1.2), 
    (extra digits:1.2),(fewer digits;1.2),
  params_cycle: -1
  params_pos_1:
    phone_lora: "<lora:PhoneExposurePDXL:1>,phone exposure,phone pov"
    character_lora: "<lora:Char-ZZZ-Belle-Pony-V1:0.9>,belle (zenless zone zero)"
    character_cloth: |
      single fingerless glove,black shirt,single thighhigh,earrings,
      hairclip,sneakers,layered skirt,single sock,
      sleeveless jacket,asymmetrical legwear,necklace,bracelet
    posture: [
      "nude, fellatio, blowjow, licking penis",
      "nude, penetration, vaginal, pussy",
      "nude, doggystyle position, vaginal, penetration",
      "nude, foggy, penetration, vaginal",s
      "nude, split, leg up, standing sex, penetration, vaginal, pussy, pussy juice",
      "nude, missionary position, penetration, pussy juice",
      "nude, cowgirl position, penetration, pussy juice",
      "nude, female masturation, grabbing own breasts",
      "nude, top-down_bottom-up, face focus, bottomless, sex from behind",
      "nude, v hand, peace sign, spread pussy, cum on body",
    ]
    common: ""
    facial_expression: [
      "blush, embarrass",
      "blush, black blindfold, open mouth, saliva",
      # "blush, mouth gag, saliva",
      "blush, embarrass, open mouth, saliva trail",
      "blush, embarrass, open mouth, saliva trail, tongue out",
      "blush, embarrass, (looking to the side:1.1)",
    ]
    scene: [
    ]

sampler:
  active: true
  name: "Euler a"
  steps: 26
  cfg_scale: 6
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
    denoising_strength: 0.33
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 1
  use_async: true
  metadata_key: "b_pox_b"

extra:
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  #file_format: "./output/%Y%m%d/belle/0/%H%M%S"
  file_format: "D:/snapshot/character/hoyoverse/zenless_zone_zero/belle/%Y%m%d/0_phone/%H%M%S"
  file_extension: "png"

