server:
  host: 127.0.0.1
  port: 30001
  progress_poll_delay: 3
  progress_poll_interval: 15
  verbose: true

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 3

prompt:
  positive: |
    1girl, solo, 
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$expressive_h$$,
    $$common$$,
    $$posture$$,
    $$act$$,   
    $$act_sub$$,
    $$act_by$$,
    $$body$$,    
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,    
    $$scene$$,
  negative: |
    (score_5,score_4,score_3,score_2,score_1),
    (text:1.2), (logo:1.2), (watermark:1.2),
    (bad anatomy:1.2),
    (extra legs：1.2),(extra hands:1.2), 
    (extra digits:1.2),(fewer digits;1.2),
  params_cycle: -1
  params_pos_1:
    character_lora: "<lora:shiori-3d-pony-6-lokr-5-c16-1-r1-000008:0.9>, KanKanShiori"
    character: |
      blue eyes,
      brown hair,multicolored hair, 
      (brown dress:0.9), (white shirt:0.9), (bell:0.9), 
      skirt, frills, thigh strap, headwear, animal ears,
    expressive_h: ""
    # expressive_h: "<lora:Expressive_H:1>,expressiveh"
    common: ""
    posture: [
      "pov, from above, paw pose, wariza, w_sitting",
      # "wariza, w_sitting, ass, barefeet, from back",
      # "barefoot, (foot focus:0.9), from below, open mouth, finger to mouth"
      # "all fours, open mouth, tongue out, from side",
      # "paw pose, open mouth, tongue out, from above, pov",
    ]
    act: [

    ]
    act_sub: [
    ]
    act_by: [

    ]
    body: [

    ]
    perspective: [

    ]
    facial_expression: [
      "blush",
    ]
    facial_expression_sub: [

    ]
    scene: [
      "fantasy, epic, aesthetic, artistic, european decora, light, dawn, light particles"
    ]


sampler:
  active: true
  name: "Euler a"
  steps: 20
  cfg_scale: 5
  seed: -1

upscaler:
  enable: false
  scale: 1.2
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 5
  use_async: true
  metadata_key: "b_pox_b"

extra:
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  file_format: "D:/snapshot/virtua_real/shiori/image/20240710_3d/0/%H%M%S"
  file_extension: "png"

