server:
  host: 127.0.0.1
  port: 30002
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: true

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 6

prompt:
  positive: |
    1girl, solo, 
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$expressive_h$$,
    $$common$$,
    $$posture_ref$$,
    $$posture$$,    
    $$body$$,    
    $$body_sub$$,
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,    
    $$scene$$,
  negative: |
    (score_6,score_5,score_4,score_3,score_2,score_1),
    (text:1.2), (logo:1.2), (watermark:1.2),
    (bad anatomy:1.2),
    (extra legs：1.2),(extra hands:1.2), 
    (extra digits:1.2),(fewer digits;1.2),
  params_cycle: -1
  params_pos_1:
    # expressive_h: "<lora:Expressive_H:1>,expressiveh"
    character_lora: "<lora:shiori-white-pony-6-lokr-5-c-16-1-r2-000016:0.9>"
    character: |
      KanKanShiori,      
      streaked hair, light brown hair, medium hair, (two side up:0.5),
      (blue eyes:0.5), 
      (blue skirt:0.5),
      (white thighhighs:0.8),
    body: [
      "",
      "beret, bareshoulders",
      "beret, coat, open clothes",
      "hood up, coat, open clothes",
      "hood up, coat, open clothes",
    ]
    body_sub: [
      "",
      "round eyewear"
    ]
    common: ""
    posture_ref: |
      <OvO des="list">
        <d src="file" base="./config/sd/preset/0_posture/">
          <i>back.yaml</i>
        </d>        
      </OvO>
    posture: [

    ]
    perspective: [

    ]
    facial_expression: [
      "blush",
    ]
    facial_expression_sub: [
      "embarrassed",
      "open mouth",
      "open mouth, tongue out",
    ]
    scene: [
      "simple background, black background, light and shadow"
    ]


sampler:
  active: true
  name: "Euler a"
  steps: 26
  cfg_scale: 5
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
    denoising_strength: 0.3
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 2
  use_async: true
  metadata_key: "b_pox_b"

extra:
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  file_format: "D:/snapshot/virtua_real/shiori/image/%Y%m%d/1_test/%H%M%S"
  file_extension: "png"

