[
  "spread legs, peace sign, v hand, cum in pussy, cum on body, looking to the side",
  "spread legs, peace sign, v hand, spread pussy by own hand, cum in pussy, cum on body, open mouth, tongue out",
  "from back, ass, pussy, cum in pussy, cum on body, grab ass by own hands",
  "squat, paw pose, cum in pussy, cum on body, open mouth, tongue out, pussy",
  "from behind, top-down_bottom-up, cum in pussy, cum on body, pussy, ass",
  "from above, pov, cum in mouth, open mouth, tongue out, v hand, peace sign",
]