server:
  host: 127.0.0.1
  port: 30001

prompt:
  positive: |
    a beautiful girl
  negative: |
    low quality, bad anatomy

image_latent:
  width: 1024
  height: 1024
  batch_size: 2
  batch_count: 1

sampler:
  active: true
  name: "Euler a"
  steps: 20
  cfg_scale: 7
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

options:
  use_async: true

output:
  file_format: "./output/%Y%m%d/test_%H%M%S"
  file_extension: "png"

