server:
  host: 127.0.0.1
  port: 30002
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: true

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 3

prompt:
  positive: |
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$expressive_h$$,
    $$common$$,
    $$people$$,
    $$posture_ref$$,
    $$posture$$,    
    $$body$$,    
    $$body_sub$$,
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,
    $$nudity_100$$,
    $$scene$$,
  negative: |
    score_6, score_5, score_4, score_3, score_2, score_1, pony, 
    worst quality, low quality, lowres, 
    bad hands, extra fingers, distorted hands, distorted fingers, missing fingers, 
    bad feet, distorted feet, distorted toes, missing toes, fewer digits, extra digits, 
    bad anatomy, 
    text, signature, watermark, logo,
    (looking at viewer:1.5), (blue hair),
    $$neg_extra$$,
  params_cycle: -1
  # Params Positive 1 ==========================================================
  params_pos_1:
    common: ""
    expressive_h: <lora:Expressive_H:${rand|0.00~0.01}>,expressiveh
    character_lora: |
      <OvO des="list">
        <d src="file" base="./config/sd/preset/0_character/">
          <i a="1" args="kafka.L:1+Min">hoyoverse/starrail.py</i>
          <i a="0" args="zhuyuan.L+C01">hoyoverse/zzz.py</i>
          <i a="0" args="firefly.L+C">hoyoverse/starrail.py</i>          
        </d>
      </OvO>
    character: ""
    people: [
      # "1girl, multiple boys, orgy"
    ]
    posture_ref: |
      <OvO des="list">
        <d a="1" src="file" base="config/sd/preset/0_posture/">          
          <i a="1" args="mouth">r18.py</i>
          <i a="1" args="breast">r18.py</i>
          <i a="1" args="hand">r18.py</i>
          <i a="1" args="pussy">r18.py</i>          
          <i a="1" args="ass">r18.py</i>
          <i a="1" args="feet">r18.py</i>
          <i a="1" args="expose">r18.py</i>
          <i a="1" args="front">r18.py</i>
          <i a="1" args="back">r18.py</i>
          <i a="1" args="top">r18.py</i>
          <i a="1" args="standing">r18.py</i>
          <i a="1" args="lying">r18.py</i>
          <i a="1" args="after">r18.py</i>
        </d>      
      </OvO>
    posture: [
    ]
    body: [
      "(half nude:$$nudity$$), torn clothes",
      "(nude:$$nudity$$)",
      "(lingerie:${rand|1.0~1.25}), (nude:$$nudity$$) (bondage:${rand|0.75~1.25})",
      "(bondage:${rand|1.0~1.75}), (nude:$$nudity$$)",
    ]
    body_sub: [
    ]
    _perspective: [
      "from back",
      "from side",
      "(from side:1.5)",
      "from above",
      "from below",
      "pov, close-up",
      "distant",
    ]
    facial_expression: [
      "embarrassed",
      "embarrassed, (looking to the side:${rand|1.05~1.25})",
      "open mouth",
      "open mouth, tongue out",
      # "tape gag",
      # "black blindfold, open mouth",
    ]
    facial_expression_sub: [
      "blush, (saliva trail:${rand|0.6~0.9})"
    ]
    scene: [
      "indoors, day",
      "indoors, night",
      "indoors, light and shadow",
      "indoors, bathroom, day",
      "indoors, bathroom, night",
      "indoors, bedroom, day",
      "indoors, bedroom, night",
      # "bedroom, indoors",
      # "office, indoors",
    ]
  # Params Positive 2 ==========================================================
  params_pos_2:
    nudity: ${rand|1~1.5}
    nudity_100: (completely nude:${rand|0.75~1.25})
  params_neg_1:
    neg_extra: ""


sampler:
  name: "Euler a"
  steps: 20
  cfg_scale: 5
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
    denoising_strength: 0.33
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 2
  use_async: true
  metadata_key: "b_pox_b"

extra:
  enable: false
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  file_format: "D:/snapshot/character/hoyoverse/zzz/kafka/%Y%m%d/0_nai/%H%M%S"
  file_extension: "png"

