server:
  host: 127.0.0.1
  port: 30002
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: true

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 12

_model:
  _base: |
    <OvO des="list">
      <d a="0" src="file" base="./config/sd/preset/">
        <i a="1" args="nai3">model.py</i>                    
      </d>
    </OvO>  

prompt:
  positive: |
    $$quality$$,
    $$quality_pony$$,    
    $$expressive_h$$,
    $$common$$,
    $$people$$,
    $$posture_ref$$,
    $$posture$$,    
    $$body$$,    
    $$body_sub$$,
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,
    $$nudity_100$$,
    $$scene$$,
  negative: |
    score_6, score_5, score_4, score_3, score_2, score_1, pony, 
    (worst quality:2),(low quality:2),(normal quality:2), lowres,     
    bad anatomy, extra digits, fewer digits, 
    text, signature, watermark, logo,
    (looking at viewer:1.2), 
    $$neg_extra$$,
  params_cycle: -1
  # Params Positive 1 ==========================================================
  params_pos_1:
    common: ""
    _quality: |
      (masterpiece:1.2),(best quality:1.2),(very aesthetic:1.2),(absurdres:1.2),
      (detailed background),(extremely detailed),newest,
    quality_pony: |
      (score_9, score_8_up, score_7_up, source_anime, rating_all, rating_explicit),
    expressive_h: <lora:Expressive_H:${rand|0.95~1.0}>,expressiveh
    character_lora: |
      <OvO des="list">
        <d src="file" base="./config/sd/preset/0_character/">
          <i a="1" args="kaguya.L:Pony01+C:School">anime/kaguya_sama.py</i>
          <i a="0" args="asuka.C:Plugsuit">anime/eva.py</i>
          <i a="0" args="yun_li.L:Pony+C:0">hoyoverse/starrail.py</i>
          <i a="0" args="hina.L:Pony+C:App+C:Coat">game/blue_archive.py</i>
          <i a="0" args="ruan_mei.L:Pony+C">hoyoverse/starrail.py</i>
          <i a="0" args="ellen_joe.L:Pony+C">hoyoverse/zzz.py</i>
          <i a="0" args="kaoruko.L:Pony+C:Stage">anime/shoujo_kageki.py</i>
          <i a="0" args="kaoruko.L:Pony+C:School">anime/shoujo_kageki.py</i>
          <i a="0" args="alisa.L:0+C">anime/keroro.py</i>
          <i a="0" args="kafka.L:1+Min+Rand">hoyoverse/starrail.py</i>
          <i a="0" args="zhuyuan.L:Pony+C:1">hoyoverse/zzz.py</i>
          <i a="0" args="firefly.L+C">hoyoverse/starrail.py</i>          
        </d>
      </OvO>
    lw: "0.935"
    character: ""
    people: [
      "1girl",
      # "1girl, orgy",
      # "1girl, multiple boys, orgy",
    ]
    posture_ref: |
      <OvO des="list">
        <d a="1" src="file" base="config/sd/preset/0_posture/">          
          <i a="1" args="mouth">r18.py</i>
          <i a="1" args="mouth_after">r18.py</i>
          <i a="1" args="breast">r18.py</i>
          <i a="1" args="hand">r18.py</i>
          <i a="1" args="pussy">r18.py</i>          
          <i a="1" args="ass">r18.py</i>
          <i a="1" args="feet">r18.py</i>
          <i a="1" args="expose">r18.py</i>
          <i a="1" args="bdsm">r18.py</i>
          <i a="1" args="front">r18.py</i>
          <i a="1" args="back">r18.py</i>
          <i a="1" args="doggy">r18.py</i>
          <i a="1" args="top">r18.py</i>
          <i a="1" args="standing">r18.py</i>
          <i a="1" args="lying">r18.py</i>
          <i a="1" args="sex_after">r18.py</i>          
        </d>      
      </OvO>
    posture: [
    ]
    body: [
      "(half nude:$$nudity$$), (torn clothes:${rand|0.5~1})",
      "(nude:$$nudity$$)",
      "(lingerie:${rand|0.5~0.75}), (nude:$$nudity$$) (bondage:${rand|0.5~1})",
      "(bondage:${rand|0.75~1.25}), (nude:$$nudity$$)",
    ]
    body_sub: [
    ]
    _perspective: [
      "from back",
      "from side",
      "(from side:1.5)",
      "from above",
      "from below",
      "pov, close-up",
      "distant",
    ]
    facial_expression: [
      "(embarrassed:${rand|0.5~0.8})",
      "(embarrassed:${rand|0.5~0.8}), (looking to the side:${rand|1.05~1.25})",
      "(confused:${rand|0.5~0.8}), (open mouth:${rand|0.0~1.0})",
      "open mouth",
      "open mouth, tongue out",
      "(female orgasm:${rand|0.65~1.0}), (rolling eyes:${rand|0.0~0.5})",
      # "tape gag",
      # "mouth gag",
      # "black blindfold, open mouth",
    ]
    facial_expression_sub: [
      "blush, (saliva trail:${rand|0.35~0.75})"
    ]
    scene: [
      # "simple background"
      "classroom",
      "school",
      "bedroom",
      "indoors",
      # "stage",
      # "bathroom",
      # "indoors",
      # "indoors, day",
      # "indoors, night",
      # "indoors, light and shadow",
      # "indoors, bathroom, day",
      # "indoors, bathroom, night",
      # "indoors, bedroom, day",
      # "indoors, bedroom, night",
      # "bedroom, indoors",
      # "office, indoors",
    ]
  # Params Positive 2 ==========================================================
  params_pos_2:
    nudity: ${rand|0.0~0.7}
    _nudity_100: (completely nude:${rand|0.0~0.7})
  params_neg_1:
    neg_extra: "shoes"


sampler:
  name: "Euler a"
  steps: 26
  cfg_scale: 4
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
    denoising_strength: 0.35
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 5
  use_async: true
  metadata_key: "b_pox_b"

extra:
  enable: false
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  file_format: D:/snapshot/character/anime/kaguya-sama/kaguya/%Y%m%d/0_nai/%H%M%S
  # file_format: "D:/snapshot/character/hoyoverse/starrail/yun_li/%Y%m%d/0_nai_bond/%H%M%S"
  # file_format: D:/snapshot/character/anime/eva/asuka/%Y%m%d/0_nai_new/%H%M%S
  # file_format: D:/snapshot/character/game/blue_archive/hina/%Y%m%d/0_nai_oral/%H%M%S
  # file_format: "D:/snapshot/character/hoyoverse/zzz/ellen_joe/%Y%m%d/0_nai_foot/%H%M%S"
  # file_format: D:/snapshot/character/anime/shoujo_kageki/kaoruko/%Y%m%d/0_nai_class/%H%M%S
  # file_format: "D:/snapshot/character/anime/keroro/alisa/%Y%m%d/1_ani/%H%M%S"
  # file_format: "D:/snapshot/character/hoyoverse/zzz/zhuyuan/%Y%m%d/0_nai_bondage/%H%M%S"
  # file_format: "D:/snapshot/character/hoyoverse/starrail/kafka/%Y%m%d/0_nai/%H%M%S"
  file_extension: "png"

