server:
  host: 127.0.0.1
  port: 30002
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: true

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 10

prompt:
  positive: |
    1girl, solo, 
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$nai_lora$$,
    $$expressive_h$$,
    $$common$$,
    $$posture_ref$$,
    $$posture$$,    
    $$body$$,    
    $$body_sub$$,
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,    
    $$scene$$,
  negative: |
    score_6, score_5, score_4, score_3, score_2, score_1, 
    (worst quality:1),(low quality:1),(normal quality:1), lowres,     
    bad anatomy, extra digits, fewer digits, 
    text, signature, watermark, logo,
    (looking at viewer:1.2),
    pussy, nipples, anus, censored, (nsfw:1),
    $$neg_extra$$,
  params_cycle: -1
  params_pos_1:
    nai_lora: <lora:naipf:0.8>
    _expressive_h: <lora:Expressive_H:1>,expressiveh
    character_lora: |
      <OvO src="file" des="list" base="./config/sd/preset/0_character/">
        <d base="anime">
          <i a="0" args="rei.C:App+C:Plugsuit">eva.py</i>
        </d>        
        <d base="v">
          <i a="1" args="shiori.white.L:Fuse+C:Hat">vr.py</i>
          <i a="0" args="dousha.sunglass.L">psplive.py</i>
          <i a="0" args="byb0.game">psplive.py</i>          
        </d>
      </OvO>
    character: ""
    body: [
      "",
      "(own hands together), clenched hands, hands up",
      "(hand on own face:$[rand|0.7~1.0])",
      "(hand on own chest:$[rand|0.7~1.0])",
      "(arm up:$[rand|0.7~1.0])",
      "(arm over shoulder:$[rand|0.7~1.0])",
      "(arm over head:$[rand|0.7~1.0])",
    ]
    body_sub: [
      "",
    ]
    common: ""
    posture_ref: |
      <OvO des="list">
        <d a="1" src="file" base="config/sd/preset/0_posture/">          
          <i a="0" args="mouth">r17.py</i>
          <i a="0" args="breast">r17.py</i>
          <i a="0" args="hand">r17.py</i>
          <i a="0" args="pussy">r17.py</i>          
          <i a="1" args="ass">r17.py</i>
          <i a="0" args="feet">r17.py</i>
          <i a="0" args="expose">r17.py</i>
          <i a="0" args="front">r17.py</i>
          <i a="1" args="back">r17.py</i>
          <i a="0" args="top">r17.py</i>
          <i a="0" args="standing">r17.py</i>
          <i a="0" args="lying">r17.py</i>
          <i a="0" args="after">r17.py</i>
          <i a="0" args="gun">r17.py</i>
        </d>      
      </OvO>
    _posture: |
      from back, 
      (holding cellphone:1.05), holding, selfie, female pov, reflection,  
      w_sitting, wariza, back, thighs, legs, barefoot,
    _perspective: [
      "from back",
      "from side",
      "(from side:1.5)",
      "from above",
      "from below",
      "pov, close-up",
      "distant",
    ]
    facial_expression: [
      "(blush:$[rand|0.6~1.0])",
      # "light blush, round eyewear"
    ]
    facial_expression_sub: [
      "",
      "open mouth",
      "(embarrassed:$[rand|0.5~0.7])",
      "(embarrassed:$[rand|0.5~0.75]), (looking to the side:$[rand|1.05~1.35])",
      # "(confused:$[rand|0.6~0.9]), (open mouth:$[rand|0.0~1.0])",
      # "pout",
      # "light smile, open mouth",
      # "pout",
      # "pout",
      # "embarrassed",
    ]
    scene: [
      # "simple background",
      # "indoors",
      # "beach, (seagull:0.6)",
      # "european architecture,indoors",
    ]

sampler:
  name: "Euler a"
  steps: 20
  cfg_scale: 4
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
    denoising_strength: 0.33
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 6
  use_async: true
  metadata_key: "b_pox_b"

extra:
  enable: false
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  # dir_path: D:/snapshot/character/
  # file_format: anime/eva/rei/%Y%m%d/0_nai/%H%M%S
  # file_format: D:/snapshot/psplive/dousha/image/%Y%m%d/0_bikini/%H%M%S
  file_format: D:/snapshot/virtua_real/shiori/image/%Y%m%d/1_dog_back/%H%M%S
  file_extension: "png"

