server:
  host: 127.0.0.1
  port: 30002
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: true

image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 3

prompt:
  positive: |
    1girl, solo, 
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$expressive_h$$,
    $$common$$,
    $$posture_ref$$,
    $$posture$$,    
    $$body$$,    
    $$body_sub$$,
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,    
    $$scene$$,
  negative: |
    score_6, score_5, score_4, score_3, score_2, score_1, pony, 
    worst quality, low quality, lowres, 
    bad hands, extra fingers, distorted hands, distorted fingers, missing fingers, 
    bad feet, distorted feet, distorted toes, missing toes, fewer digits, extra digits, 
    bad anatomy, 
    text, signature, watermark, logo,
    (looking at viewer:1.5), (shoes:1.5)
  params_cycle: -1
  params_pos_1:
    _expressive_h: "<lora:Expressive_H:1>,expressiveh"
    character_lora: |
      <OvO des="list">
        <d src="file" base="./config/sd/preset/0_character/">
          <i a="1" args="dousha.sunglass.L">psplive.py</i>
          <i a="0" args="byb0.game">psplive.py</i>          
        </d>
      </OvO>
    character: |
      DoushaBare, 
      headwear on head, (sunglasses:0.5), 
      long hair,streaked hair,multicolored hair,
      side braid, panda ears,              
      blue eyes,       
      single thigh strap, anklet,
      black and white string bikini, no shoes,
    body: [
      "",
    ]
    body_sub: [
      "",
    ]
    common: ""
    posture_ref: |
      <OvO des="list">
        <d a="1" src="file" base="config/sd/preset/0_posture/">          
          <i a="0" args="mouth">r17.py</i>
          <i a="0" args="breast">r17.py</i>
          <i a="0" args="hand">r17.py</i>
          <i a="0" args="pussy">r17.py</i>          
          <i a="0" args="ass">r17.py</i>
          <i a="0" args="feet">r17.py</i>
          <i a="0" args="expose">r17.py</i>
          <i a="0" args="front">r17.py</i>
          <i a="1" args="back">r17.py</i>
          <i a="0" args="top">r17.py</i>
          <i a="0" args="standing">r17.py</i>
          <i a="0" args="lying">r17.py</i>
          <i a="0" args="after">r17.py</i>
        </d>      
      </OvO>
    _posture: |
      from back, 
      (holding cellphone:1.05), holding, selfie, female pov, reflection,  
      w_sitting, wariza, back, thighs, legs, barefoot,
    _perspective: [
      "from back",
      "from side",
      "(from side:1.5)",
      "from above",
      "from below",
      "pov, close-up",
      "distant",
    ]
    facial_expression: [
      "light blush",
    ]
    facial_expression_sub: [
      "open mouth",
      "embarrassed",
      "light smile, open mouth",
      # "pout",
      # "pout",
      # "embarrassed",
    ]
    scene: [
      # "simple background",
      # "indoors",
      "beach, (seagull:0.6)",
    ]

sampler:
  name: "Euler a"
  steps: 20
  cfg_scale: 5
  seed: -1

upscaler:
  enable: true
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
    denoising_strength: 0.3
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 2
  use_async: true
  metadata_key: "b_pox_b"

extra:
  enable: false
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  file_format: D:/snapshot/psplive/dousha/image/%Y%m%d/0_bikini/%H%M%S
  # file_format: D:/snapshot/virtua_real/shiori/image/%Y%m%d/7_pos/%H%M%S
  file_extension: "png"

