server:
  host: 127.0.0.1
  port: 30001

prompt:
  positive: |
    a beautiful girl,
    $$lora_main$$,
    $$eye$$,
    $$hair$$,
  negative: |
    low quality, bad anatomy
  params_pos:
    lora_main: "MY LORA!"
    eye: [
      "red eyes", "blue eyes"
    ]
    hair: [
      "white hair", "black hair", "blonde hair"
    ]


image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 1

sampler:
  active: true
  name: "Euler a"
  steps: 20
  cfg_scale: 7
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: false
    model: "face_yolov8n.pt"
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 0.1
  use_async: true

output:
  file_format: "./output/%Y%m%d/test/%H%M%S"
  file_extension: "png"

