server:
  host: 127.0.0.1
  port: 30002
  progress_poll_delay: 1024
  progress_poll_interval: 1024
  verbose: true


image_latent:
  width: 1024
  height: 1024
  batch_size: 1
  batch_count: 3

prompt:
  positive: |
    (score_9, score_8_up, score_7_up, source_anime, rating_all),
    $$expressive_h$$,
    $$common$$,
    $$posture$$,
    $$act$$,   
    $$act_sub$$,
    $$act_by$$,
    $$body$$,    
    $$character_lora$$,
    $$perspective$$,
    $$character$$,
    $$facial_expression$$,
    $$facial_expression_sub$$,    
    $$scene$$,
  negative: |
    score_6,score_5,score_4,score_3,score_2,score_1,
    censored,
    (text:1.2), (logo:1.2), (watermark:1.2),
    (bad anatomy:1.2),
    (extra legs：1.2),(extra hands:1.2), 
    (extra digits:1.2),(fewer digits;1.2),
    (looking at viewer:1.2),
  params_cycle: -1
  params_pos_1:
    character_lora: ""
    __character: |
      <lora:ellen_joe_pony:0.9>,
      1girl,ellen_joe,maid_headdress,red eyes,
      black_dress,wrist_cuffs,puffy_short_sleeves,mole_under_eye,large_breasts,frilled_dress,black_pantyhose
    character: |
      <lora:firefly_V3_pony:1>, firefly_\(honkai:_star_rail\),
      (black_hairband:0.8), 
      (yellow_neckerchief:0.8), (black_jacket:0.8), 
      (sailor_jacket:0.8), (hair_intakes:0.8), (aqua_skirt:0.8)
    expressive_h: <lora:Expressive_H:1>,expressiveh
    common: ""
    posture: |
      <OvO des="list">
        <d active="1" src="file" base="config/sd/preset/0_posture/nsfw/"/>
          <i active="1">after.py</i>
          <i active="1">back.py</i>
          <i active="1">chest.py</i>
          <i active="1">expose.py</i>
          <i active="1">front.py</i>
          <i active="1">hand.py</i>
          <i active="1">lying.py</i>
          <i active="1">mouth.py</i>
          <i active="1">stand.py</i>
          <i active="1">top.py</i>
        </d>
        <d active="1" src="file" base="config/sd/preset/0_posture/safe/"/>
        </d>
      </OvO>
    act: [
    ]
    act_sub: [
    ]
    act_by: [
      ""
    ]
    __body: [
    ]
    body: [
      # "(half nude:0.5)",
      # "half nude",
      "half nude, torn clothes",
      "(nude:0.65)",
      "(nude:0.85)",
      "(nude:1.05)",
      "lingerie, (nude:0.6)",
      "lingerie, (nude:0.8)",
      "bondage, (nude:0.65)",
      "bondage, (nude:0.85)",
      "bondage, (nude:0.85), (saliva trail:0.5)",
    ]
    perspective: [

    ]
    facial_expression: [
      "embarrassed",
      "embarrassed, looking to the side",
      "open mouth",
      "open mouth, tongue out",
      # "black blindfold, open mouth",
    ]
    facial_expression_sub: [
      "blush, (saliva trail:0.75)"
    ]
    scene: [
      "outdoors, night, (night sky:0.5), (fireflies:0.5), (light particles:0.1), aesthetic",
    ]


sampler:
  active: true
  name: "Euler a"
  steps: 26
  cfg_scale: 5
  seed: -1

upscaler:
  enable: false
  scale: 1.25
  second_pass_steps: 10
  denoising_strength: 0.5
  name: "ESRGAN_4x_Anime6B"

adetailers:
  - enable: true
    model: "face_yolov8n.pt"
    denoising_strength: 0.3
  - enable: false
    model: "hand_yolov8n.pt"

options:
  colddown: 2
  use_async: true
  metadata_key: "b_pox_b"

extra:
  upscaler_1: "ESRGAN_4x_Anime6B"
  upscaling_resize: 1.25

output_txt2img:
  #file_format: "./output/%Y%m%d/belle/0/%H%M%S"
  file_format: "D:/snapshot/character/hoyoverse/starrail/firefly/%Y%m%d/0/%H%M%S"
  file_extension: "png"

